on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

name: Windows build
jobs:
    test-windows:
        runs-on: windows-latest
        strategy:
            matrix:
                python-version: ["3.12"]

        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v6
              with:
                  version: "0.4.16"
                  enable-cache: false

            - name: Install dependencies
              run: |
                  uv venv --python ${{ matrix.python-version }}
                  uv pip install .

            # - name: Update PROJ data files
            #   run: |
            #       pip install --upgrade pyproj
            #       curl -L -o proj-data.zip https://download.osgeo.org/proj/proj-data-1.9.zip
            #       unzip proj-data.zip -d proj-data
            #       cp -r proj-data/* $(python -m pyproj -v | grep "PROJ_LIB" | cut -d ' ' -f 2)

            - name: Test import
              run: |
                  uv run python -c "import mapwidget; print('mapwidget import successful')"
